# fly.toml app configuration file generated for google-scrapper-ruby-prod on 2023-06-16T16:27:15+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "google-scrapper-ruby"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
