# fly.toml app configuration file generated for google-scrapper-ruby-prod on 2023-06-16T16:27:15+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "google-scrapper-ruby"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[env]
  RAILS_ENV = "production"
  MAILER_DEFAULT_HOST = "localhost"
  MAILER_DEFAULT_PORT = "80"
  MAILER_SENDER = "Test <noreply@nimblehq.co>"
  AVAILABLE_LOCALES = "en"
  DEFAULT_LOCALE = "en"
  FALLBACK_LOCALES = "en"
  RAILS_LOG_TO_STDOUT = true

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
